// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​l​f​a​V​o​i​c​e
	 */
	appName: string
	/**
	 * D​i​c​t​i​o​n​a​r​y
	 */
	dictionary: string
	/**
	 * S​n​i​p​p​e​t​s
	 */
	snippets: string
	/**
	 * N​o​t​e​s
	 */
	notes: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * S​u​p​p​o​r​t
	 */
	support: string
	/**
	 * T​o​g​g​l​e​ ​s​i​d​e​b​a​r
	 */
	toggleSidebar: string
	/**
	 * E​n​a​b​l​e​ ​l​i​g​h​t​ ​t​h​e​m​e
	 */
	enableLightTheme: string
	/**
	 * E​n​a​b​l​e​ ​d​a​r​k​ ​t​h​e​m​e
	 */
	enableDarkTheme: string
	/**
	 * N​o​t​i​f​i​c​a​t​i​o​n​s
	 */
	notifications: string
	/**
	 * M​a​r​k​ ​a​l​l​ ​a​s​ ​r​e​a​d
	 */
	markAllAsRead: string
	/**
	 * S​h​o​w​ ​a​l​l
	 */
	showAll: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	goToSettings: string
	/**
	 * M​i​n​i​m​i​z​e
	 */
	minimize: string
	/**
	 * M​a​x​i​m​i​z​e
	 */
	maximize: string
	/**
	 * C​l​o​s​e
	 */
	close: string
	/**
	 * S​y​n​c
	 */
	sync: string
	/**
	 * S​y​n​c​i​n​g​.​.​.
	 */
	syncing: string
	/**
	 * S​y​n​c​e​d
	 */
	synced: string
	/**
	 * S​y​n​c​ ​e​r​r​o​r
	 */
	syncError: string
	/**
	 * L​a​s​t​ ​s​y​n​c
	 */
	lastSync: string
	/**
	 * P​e​n​d​i​n​g​ ​c​h​a​n​g​e​s
	 */
	pendingChanges: string
	/**
	 * G​o​ ​t​o​ ​h​o​m​e
	 */
	goToHome: string
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	dashboardTitle: string
	/**
	 * W​e​l​c​o​m​e​ ​b​a​c​k​,​ ​{​{​n​a​m​e​}​}
	 */
	welcomeBack: string
	/**
	 * P​r​o​d​u​c​t​i​v​i​t​y​ ​o​v​e​r​v​i​e​w
	 */
	productivityOverview: string
	/**
	 * R​e​c​o​r​d​i​n​g​ ​i​n​ ​p​r​o​g​r​e​s​s​.​.​.
	 */
	recordingInProgress: string
	/**
	 * d​a​y​s​ ​l​e​f​t
	 */
	daysLeft_days: string
	/**
	 * d​a​y​ ​l​e​f​t
	 */
	daysLeft_day: string
	/**
	 * d​a​y​s​ ​l​e​f​t
	 */
	daysLeft_days2_4: string
	/**
	 * w​o​r​d​s
	 */
	wordsCount: string
	/**
	 * W​P​M
	 */
	wpmLabel: string
	/**
	 * M​a​k​e​ ​A​l​f​a​V​o​i​c​e​ ​s​o​u​n​d​ ​l​i​k​e​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​t​e​x​t​-​p​r​i​m​a​r​y​ ​i​t​a​l​i​c​ ​f​o​n​t​-​s​e​r​i​f​"​>​y​o​u​<​/​s​p​a​n​>
	 */
	personalizeTitle: string
	/**
	 * A​l​f​a​V​o​i​c​e​ ​a​d​a​p​t​s​ ​t​o​ ​y​o​u​r​ ​c​o​r​p​o​r​a​t​e​ ​t​o​n​e​ ​a​c​r​o​s​s​ ​a​l​l​ ​p​l​a​t​f​o​r​m​s​.​ ​P​e​r​s​o​n​a​l​i​z​e​ ​y​o​u​r​ ​w​r​i​t​i​n​g​ ​s​t​y​l​e​ ​f​o​r​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​s​e​m​i​b​o​l​d​ ​t​e​x​t​-​t​e​x​t​-​m​a​i​n​ ​d​a​r​k​:​t​e​x​t​-​w​h​i​t​e​"​>​m​e​s​s​a​g​e​s​,​ ​c​l​i​e​n​t​ ​e​m​a​i​l​s​,​ ​a​n​d​ ​i​n​t​e​r​n​a​l​ ​c​h​a​t​s​<​/​s​p​a​n​>​ ​t​o​ ​e​n​s​u​r​e​ ​b​r​a​n​d​ ​c​o​n​s​i​s​t​e​n​c​y​.
	 */
	personalizeDescription: string
	/**
	 * S​t​a​r​t​ ​p​e​r​s​o​n​a​l​i​z​a​t​i​o​n
	 */
	startPersonalization: string
	/**
	 * I​n​t​e​g​r​a​t​i​o​n​s
	 */
	integrations: string
	/**
	 * D​e​v​e​l​o​p​m​e​n​t
	 */
	development: string
	/**
	 * V​S​ ​C​o​d​e​ ​E​x​t​e​n​s​i​o​n
	 */
	vsCodeExtension: string
	/**
	 * B​r​o​w​s​e​r
	 */
	browser: string
	/**
	 * C​h​r​o​m​e​ ​I​n​t​e​g​r​a​t​i​o​n
	 */
	chromeIntegration: string
	/**
	 * R​e​c​e​n​t​ ​a​c​t​i​v​i​t​y​ ​—​ ​{​{​d​a​t​e​}​}
	 */
	recentActivity: string
	/**
	 * V​i​e​w​ ​a​l​l​ ​h​i​s​t​o​r​y
	 */
	viewAllHistory: string
	/**
	 * T​r​a​n​s​c​r​i​b​i​n​g​.​.​.
	 */
	transcribing: string
	/**
	 * C​o​p​y​ ​t​e​x​t
	 */
	copyText: string
	/**
	 * D​e​l​e​t​e​ ​r​e​c​o​r​d​i​n​g
	 */
	deleteRecording: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settingsTitle: string
	/**
	 * M​a​n​a​g​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​s​e​t​t​i​n​g​s​ ​a​n​d​ ​y​o​u​r​ ​a​c​c​o​u​n​t​.
	 */
	settingsDescription: string
	/**
	 * G​e​n​e​r​a​l
	 */
	generalTab: string
	/**
	 * D​e​v​i​c​e​s
	 */
	devicesTab: string
	/**
	 * L​a​n​g​u​a​g​e​s
	 */
	languagesTab: string
	/**
	 * N​o​t​i​f​i​c​a​t​i​o​n​s
	 */
	notificationsTab: string
	/**
	 * P​r​i​v​a​c​y
	 */
	privacyTab: string
	/**
	 * U​s​e​r​ ​P​r​o​f​i​l​e
	 */
	userProfile: string
	/**
	 * A​c​c​o​u​n​t​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​n​d​ ​a​v​a​t​a​r​.
	 */
	userProfileDescription: string
	/**
	 * A​c​c​o​u​n​t​ ​m​a​n​a​g​e​d​ ​v​i​a​ ​L​D​A​P
	 */
	managedByLdap: string
	/**
	 * F​i​r​s​t​ ​n​a​m​e
	 */
	firstName: string
	/**
	 * L​a​s​t​ ​n​a​m​e
	 */
	lastName: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	emailAddress: string
	/**
	 * R​o​l​e
	 */
	role: string
	/**
	 * M​i​c​r​o​p​h​o​n​e
	 */
	microphone: string
	/**
	 * I​n​p​u​t​ ​d​e​v​i​c​e
	 */
	inputDevice: string
	/**
	 * N​o​ ​m​i​c​r​o​p​h​o​n​e​s​ ​f​o​u​n​d
	 */
	microphoneNotFound: string
	/**
	 * R​e​c​o​r​d​i​n​g​.​.​.
	 */
	recording: string
	/**
	 * P​l​a​y​i​n​g​.​.​.
	 */
	playing: string
	/**
	 * A​c​t​i​v​e
	 */
	active: string
	/**
	 * A​c​c​e​s​s​ ​r​e​q​u​i​r​e​d
	 */
	accessRequired: string
	/**
	 * N​o​t​ ​f​o​u​n​d
	 */
	notFound: string
	/**
	 * S​t​o​p​ ​r​e​c​o​r​d​i​n​g
	 */
	stopRecording: string
	/**
	 * S​t​o​p​ ​p​l​a​y​b​a​c​k
	 */
	stopPlayback: string
	/**
	 * S​t​a​r​t​ ​t​e​s​t
	 */
	startTest: string
	/**
	 * I​n​p​u​t​ ​l​e​v​e​l
	 */
	inputLevel: string
	/**
	 * D​e​c​r​e​a​s​e​ ​v​o​l​u​m​e
	 */
	decreaseVolume: string
	/**
	 * I​n​c​r​e​a​s​e​ ​v​o​l​u​m​e
	 */
	increaseVolume: string
	/**
	 * R​e​c​o​r​d​i​n​g​ ​w​i​l​l​ ​w​o​r​k​ ​w​h​e​n​ ​y​o​u​ ​h​o​l​d​ ​t​h​e​ ​h​o​t​k​e​y​s
	 */
	hotkeysWorkWhenHeld: string
	/**
	 * H​o​t​k​e​y​s
	 */
	hotkeys: string
	/**
	 * Q​u​i​c​k​ ​r​e​c​o​r​d​i​n​g
	 */
	quickRecording: string
	/**
	 * G​l​o​b​a​l​ ​c​o​m​b​i​n​a​t​i​o​n​ ​t​o​ ​s​t​a​r​t​/​s​t​o​p​ ​r​e​c​o​r​d​i​n​g
	 */
	quickRecordingDescription: string
	/**
	 * P​r​e​s​s​ ​k​e​y​s​.​.​.
	 */
	pressKeys: string
	/**
	 * C​h​a​n​g​e
	 */
	change: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * R​e​g​i​o​n​a​l​ ​S​e​t​t​i​n​g​s
	 */
	regionalSettings: string
	/**
	 * I​n​t​e​r​f​a​c​e​ ​l​a​n​g​u​a​g​e
	 */
	interfaceLanguage: string
	/**
	 * C​h​a​n​g​i​n​g​ ​l​a​n​g​u​a​g​e​ ​m​a​y​ ​r​e​q​u​i​r​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​r​e​l​o​a​d​.
	 */
	languageChangeNote: string
	/**
	 * T​i​m​e​z​o​n​e
	 */
	timezone: string
	/**
	 * N​o​t​i​f​i​c​a​t​i​o​n​ ​C​a​t​e​g​o​r​i​e​s
	 */
	notificationCategories: string
	/**
	 * N​o​t​i​f​i​c​a​t​i​o​n​ ​t​y​p​e
	 */
	notificationType: string
	/**
	 * E​m​a​i​l
	 */
	email: string
	/**
	 * P​u​s​h
	 */
	push: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n​ ​f​o​r​ ​{​{​t​y​p​e​}​}​.​.​.
	 */
	descriptionFor: string
	/**
	 * S​e​c​u​r​e​ ​p​e​r​i​m​e​t​e​r​ ​a​c​t​i​v​e
	 */
	securePerimeterActive: string
	/**
	 * A​p​p​l​i​c​a​t​i​o​n​ ​r​u​n​s​ ​i​n​ ​a​n​ ​i​s​o​l​a​t​e​d​ ​e​n​v​i​r​o​n​m​e​n​t​.​ ​A​l​l​ ​t​e​x​t​ ​d​a​t​a​ ​i​s​ ​e​n​c​r​y​p​t​e​d​ ​(​A​E​S​-​2​5​6​)​.​ ​C​l​o​u​d​ ​s​y​n​c​ ​i​s​ ​l​i​m​i​t​e​d​ ​b​y​ ​s​e​c​u​r​i​t​y​ ​p​o​l​i​c​y​.
	 */
	securePerimeterDescription: string
	/**
	 * C​h​e​c​k​ ​s​t​a​t​u​s
	 */
	checkStatus: string
	/**
	 * A​p​p​ ​A​c​c​e​s​s
	 */
	appAccess: string
	/**
	 * T​o​d​a​y
	 */
	today: string
}

export type TranslationFunctions = {
	/**
	 * AlfaVoice
	 */
	appName: () => LocalizedString
	/**
	 * Dictionary
	 */
	dictionary: () => LocalizedString
	/**
	 * Snippets
	 */
	snippets: () => LocalizedString
	/**
	 * Notes
	 */
	notes: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Support
	 */
	support: () => LocalizedString
	/**
	 * Toggle sidebar
	 */
	toggleSidebar: () => LocalizedString
	/**
	 * Enable light theme
	 */
	enableLightTheme: () => LocalizedString
	/**
	 * Enable dark theme
	 */
	enableDarkTheme: () => LocalizedString
	/**
	 * Notifications
	 */
	notifications: () => LocalizedString
	/**
	 * Mark all as read
	 */
	markAllAsRead: () => LocalizedString
	/**
	 * Show all
	 */
	showAll: () => LocalizedString
	/**
	 * Settings
	 */
	goToSettings: () => LocalizedString
	/**
	 * Minimize
	 */
	minimize: () => LocalizedString
	/**
	 * Maximize
	 */
	maximize: () => LocalizedString
	/**
	 * Close
	 */
	close: () => LocalizedString
	/**
	 * Sync
	 */
	sync: () => LocalizedString
	/**
	 * Syncing...
	 */
	syncing: () => LocalizedString
	/**
	 * Synced
	 */
	synced: () => LocalizedString
	/**
	 * Sync error
	 */
	syncError: () => LocalizedString
	/**
	 * Last sync
	 */
	lastSync: () => LocalizedString
	/**
	 * Pending changes
	 */
	pendingChanges: () => LocalizedString
	/**
	 * Go to home
	 */
	goToHome: () => LocalizedString
	/**
	 * Dashboard
	 */
	dashboardTitle: () => LocalizedString
	/**
	 * Welcome back, {{name}}
	 */
	welcomeBack: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Productivity overview
	 */
	productivityOverview: () => LocalizedString
	/**
	 * Recording in progress...
	 */
	recordingInProgress: () => LocalizedString
	/**
	 * days left
	 */
	daysLeft_days: () => LocalizedString
	/**
	 * day left
	 */
	daysLeft_day: () => LocalizedString
	/**
	 * days left
	 */
	daysLeft_days2_4: () => LocalizedString
	/**
	 * words
	 */
	wordsCount: () => LocalizedString
	/**
	 * WPM
	 */
	wpmLabel: () => LocalizedString
	/**
	 * Make AlfaVoice sound like <span class="text-primary italic font-serif">you</span>
	 */
	personalizeTitle: () => LocalizedString
	/**
	 * AlfaVoice adapts to your corporate tone across all platforms. Personalize your writing style for <span class="font-semibold text-text-main dark:text-white">messages, client emails, and internal chats</span> to ensure brand consistency.
	 */
	personalizeDescription: () => LocalizedString
	/**
	 * Start personalization
	 */
	startPersonalization: () => LocalizedString
	/**
	 * Integrations
	 */
	integrations: () => LocalizedString
	/**
	 * Development
	 */
	development: () => LocalizedString
	/**
	 * VS Code Extension
	 */
	vsCodeExtension: () => LocalizedString
	/**
	 * Browser
	 */
	browser: () => LocalizedString
	/**
	 * Chrome Integration
	 */
	chromeIntegration: () => LocalizedString
	/**
	 * Recent activity — {{date}}
	 */
	recentActivity: (arg0: number | string | boolean) => LocalizedString
	/**
	 * View all history
	 */
	viewAllHistory: () => LocalizedString
	/**
	 * Transcribing...
	 */
	transcribing: () => LocalizedString
	/**
	 * Copy text
	 */
	copyText: () => LocalizedString
	/**
	 * Delete recording
	 */
	deleteRecording: () => LocalizedString
	/**
	 * Settings
	 */
	settingsTitle: () => LocalizedString
	/**
	 * Manage application settings and your account.
	 */
	settingsDescription: () => LocalizedString
	/**
	 * General
	 */
	generalTab: () => LocalizedString
	/**
	 * Devices
	 */
	devicesTab: () => LocalizedString
	/**
	 * Languages
	 */
	languagesTab: () => LocalizedString
	/**
	 * Notifications
	 */
	notificationsTab: () => LocalizedString
	/**
	 * Privacy
	 */
	privacyTab: () => LocalizedString
	/**
	 * User Profile
	 */
	userProfile: () => LocalizedString
	/**
	 * Account information and avatar.
	 */
	userProfileDescription: () => LocalizedString
	/**
	 * Account managed via LDAP
	 */
	managedByLdap: () => LocalizedString
	/**
	 * First name
	 */
	firstName: () => LocalizedString
	/**
	 * Last name
	 */
	lastName: () => LocalizedString
	/**
	 * Email address
	 */
	emailAddress: () => LocalizedString
	/**
	 * Role
	 */
	role: () => LocalizedString
	/**
	 * Microphone
	 */
	microphone: () => LocalizedString
	/**
	 * Input device
	 */
	inputDevice: () => LocalizedString
	/**
	 * No microphones found
	 */
	microphoneNotFound: () => LocalizedString
	/**
	 * Recording...
	 */
	recording: () => LocalizedString
	/**
	 * Playing...
	 */
	playing: () => LocalizedString
	/**
	 * Active
	 */
	active: () => LocalizedString
	/**
	 * Access required
	 */
	accessRequired: () => LocalizedString
	/**
	 * Not found
	 */
	notFound: () => LocalizedString
	/**
	 * Stop recording
	 */
	stopRecording: () => LocalizedString
	/**
	 * Stop playback
	 */
	stopPlayback: () => LocalizedString
	/**
	 * Start test
	 */
	startTest: () => LocalizedString
	/**
	 * Input level
	 */
	inputLevel: () => LocalizedString
	/**
	 * Decrease volume
	 */
	decreaseVolume: () => LocalizedString
	/**
	 * Increase volume
	 */
	increaseVolume: () => LocalizedString
	/**
	 * Recording will work when you hold the hotkeys
	 */
	hotkeysWorkWhenHeld: () => LocalizedString
	/**
	 * Hotkeys
	 */
	hotkeys: () => LocalizedString
	/**
	 * Quick recording
	 */
	quickRecording: () => LocalizedString
	/**
	 * Global combination to start/stop recording
	 */
	quickRecordingDescription: () => LocalizedString
	/**
	 * Press keys...
	 */
	pressKeys: () => LocalizedString
	/**
	 * Change
	 */
	change: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Regional Settings
	 */
	regionalSettings: () => LocalizedString
	/**
	 * Interface language
	 */
	interfaceLanguage: () => LocalizedString
	/**
	 * Changing language may require application reload.
	 */
	languageChangeNote: () => LocalizedString
	/**
	 * Timezone
	 */
	timezone: () => LocalizedString
	/**
	 * Notification Categories
	 */
	notificationCategories: () => LocalizedString
	/**
	 * Notification type
	 */
	notificationType: () => LocalizedString
	/**
	 * Email
	 */
	email: () => LocalizedString
	/**
	 * Push
	 */
	push: () => LocalizedString
	/**
	 * Description for {{type}}...
	 */
	descriptionFor: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Secure perimeter active
	 */
	securePerimeterActive: () => LocalizedString
	/**
	 * Application runs in an isolated environment. All text data is encrypted (AES-256). Cloud sync is limited by security policy.
	 */
	securePerimeterDescription: () => LocalizedString
	/**
	 * Check status
	 */
	checkStatus: () => LocalizedString
	/**
	 * App Access
	 */
	appAccess: () => LocalizedString
	/**
	 * Today
	 */
	today: () => LocalizedString
}

export type Formatters = {}
